# Japanese translation for aptdaemon
# Copyright (c) 2009 Rosetta Contributors and Canonical Ltd 2009
# This file is distributed under the same license as the aptdaemon package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2009.
#
msgid ""
msgstr ""
"Project-Id-Version: aptdaemon\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-08-21 15:36+0200\n"
"PO-Revision-Date: 2013-01-24 01:57+0000\n"
"Last-Translator: Koichi Akabe <vbkaisetsu@gmail.com>\n"
"Language-Team: Japanese <ja@li.org>\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Launchpad-Export-Date: 2013-03-09 23:28+0000\n"
"X-Generator: Launchpad (build 16523)\n"

#: ../data/org.debian.apt.policy.in.h:1
msgid "List keys of trusted vendors"
msgstr "信頼できるベンダーの鍵を一覧表示します"

#: ../data/org.debian.apt.policy.in.h:2
msgid "To view the list of trusted keys, you need to authenticate."
msgstr "信頼している鍵のリストを表示するには、認証が必要です。"

#: ../data/org.debian.apt.policy.in.h:3 ../aptdaemon/console.py:619
msgid "Remove downloaded package files"
msgstr "ダウンロードしたパッケージファイルの削除"

#: ../data/org.debian.apt.policy.in.h:4
msgid "To clean downloaded package files, you need to authenticate."
msgstr ""
"ダウンロードしたパッケージファイルを削除するには、認証する必要があります"

#: ../data/org.debian.apt.policy.in.h:5
msgid "Change software configuration"
msgstr "ソフトウェア設定の変更"

#: ../data/org.debian.apt.policy.in.h:6
msgid "To change software settings, you need to authenticate."
msgstr "ソフトウェア設定を変更するには、認証する必要があります"

#: ../data/org.debian.apt.policy.in.h:7
msgid "Change software repository"
msgstr "ソフトウェアリポジトリの変更"

#: ../data/org.debian.apt.policy.in.h:8
msgid "To change software repository settings, you need to authenticate."
msgstr "ソフトウェアリポジトリの設定を変更するには、認証が必要です。"

#: ../data/org.debian.apt.policy.in.h:9
msgid "Install package file"
msgstr "パッケージファイルのインストール"

#: ../data/org.debian.apt.policy.in.h:10
msgid "To install this package, you need to authenticate."
msgstr "このパッケージをインストールするには、認証が必要です。"

#: ../data/org.debian.apt.policy.in.h:11
msgid "Update package information"
msgstr "パッケージ情報の更新"

#: ../data/org.debian.apt.policy.in.h:12
msgid "To update the software catalog, you need to authenticate."
msgstr "ソフトウェアカタログを更新するには、認証が必要です。"

#: ../data/org.debian.apt.policy.in.h:13
msgid "Install or remove packages"
msgstr "パッケージのインストールまたは削除"

#: ../data/org.debian.apt.policy.in.h:14
msgid "To install or remove software, you need to authenticate."
msgstr ""
"ソフトウェアをインストールまたは削除するには、認証を行う必要があります。"

#. This priviledge will be requested when installing a package
#. from a high trusted repository that can be explicitely whitelisted.
#.
#. The defaults for this action are the same as
#. "org.debian.apt.install-or-remove-packages".
#.
#. The admin can override them to e.g. allow passwordless installs for
#. leightweight applications like unity-webapps or for packages
#. comming from high trust repositories (like internal repositories)
#.
#: ../data/org.debian.apt.policy.in.h:25
msgid "Install software from a high-trust whitelisted repository."
msgstr ""
"信頼性の高いホワイトリストに載っているリポジトリからソフトウェアをインストー"
"ルします。"

#: ../data/org.debian.apt.policy.in.h:26
msgid "To install software, you need to authenticate."
msgstr "ソフトウェアをインストールするには認証が必要です。"

#. This privilege allows to call AddRepository, UpdateCache(Partially)
#. and InstallPackages in a row and only authenticating once.
#.
#. The client has to authenticate for this privilege before calling
#. the aptdaemon methods.
#: ../data/org.debian.apt.policy.in.h:32
msgid "Add a new repository and install packages from it"
msgstr "新しいリポジトリを追加してパッケージをインストールします"

#: ../data/org.debian.apt.policy.in.h:33
msgid "To install software from a new source, you need to authenticate."
msgstr "新しいソースからソフトウェアをインストールするには、認証が必要です。"

#. This privilege allows to call AddRepository, UpdateCache(Partially)
#. and InstallPackages in a row and only authenticating once.
#.
#. The client has to authenticate for this privilege before calling
#. the aptdaemon methods.
#.
#. The only difference to install-packages-from-new-repo is the wording
#. of the message. It is required by Ubuntu's Software-Center.
#: ../data/org.debian.apt.policy.in.h:42
msgid "Add a new repository of purchased software and install packages from it"
msgstr "新しいリポジトリを追加してパッケージをインストールします"

#: ../data/org.debian.apt.policy.in.h:43
msgid "To install purchased software, you need to authenticate."
msgstr "購入したソフトウェアをインストールするには、認証が必要です。"

#: ../data/org.debian.apt.policy.in.h:44
msgid "Upgrade packages"
msgstr "パッケージのアップグレード"

#: ../data/org.debian.apt.policy.in.h:45
msgid "To install updated software, you need to authenticate."
msgstr "更新されたソフトウェアをインストールするには、認証が必要です。"

#: ../data/org.debian.apt.policy.in.h:46
msgid "Cancel the task of another user"
msgstr "他のユーザのタスクの中止"

#: ../data/org.debian.apt.policy.in.h:47
msgid "To cancel someone else's software changes, you need to authenticate."
msgstr "他人によるソフトウエアの変更を防ぐため、認証が必要です"

#: ../data/org.debian.apt.policy.in.h:48
msgid "Set a proxy for software downloads"
msgstr "ソフトウェアダウンロードのためのプロキシを設定"

#: ../data/org.debian.apt.policy.in.h:49
msgid ""
"To use a proxy server for downloading software, you need to authenticate."
msgstr ""
"ソフトウェアのダウンロードにプロキシサーバーを利用するには、認証が必要です。"

#: ../aptdaemon/console.py:215
msgid "ERROR"
msgstr "エラー"

#: ../aptdaemon/console.py:249
#, fuzzy, python-format
msgid "Downloaded %(cur)sB of %(total)sB at %(rate)sB/s"
msgstr "%sB / %sB をダウンロード済（%sB/s）"

#: ../aptdaemon/console.py:255
#, fuzzy, python-format
msgid "Downloaded %(cur)sB of %(total)sB"
msgstr "%sB / %sB をダウンロード済"

#: ../aptdaemon/console.py:385 ../aptdaemon/console.py:390
msgid "ERROR:"
msgstr "エラー:"

#: ../aptdaemon/console.py:386
msgid "You are not allowed to perform this action."
msgstr "このアクションを行う権限がありません。"

#: ../aptdaemon/console.py:409 ../aptdaemon/console.py:537
msgid "Queuing"
msgstr "待機中"

#: ../aptdaemon/console.py:417 ../aptdaemon/enums.py:527
msgid "Resolving dependencies"
msgstr "依存関係を解決しています"

#. TRANSLATORS: %s is the number of packages
#: ../aptdaemon/console.py:459
#, python-format
msgid "The following NEW package will be installed (%(count)s):"
msgid_plural "The following NEW packages will be installed (%(count)s):"
msgstr[0] "以下の新しいパッケージをインストールします (%(count)s):"

#. TRANSLATORS: %s is the number of packages
#: ../aptdaemon/console.py:467
#, python-format
msgid "The following package will be upgraded (%(count)s):"
msgid_plural "The following packages will be upgraded (%(count)s):"
msgstr[0] "以下のパッケージをアップグレードします (%(count)s):"

#. TRANSLATORS: %s is the number of packages
#: ../aptdaemon/console.py:475
#, python-format
msgid "The following package will be REMOVED (%(count)s):"
msgid_plural "The following packages will be REMOVED (%(count)s):"
msgstr[0] "以下のパッケージを削除します (%(count)s):"

#. TRANSLATORS: %s is the number of packages
#: ../aptdaemon/console.py:484
#, python-format
msgid "The following package will be DOWNGRADED (%(count)s):"
msgid_plural "The following packages will be DOWNGRADED (%(count)s):"
msgstr[0] "以下のパッケージをダウングレードします (%(count)s):"

#. TRANSLATORS: %s is the number of packages
#: ../aptdaemon/console.py:492
#, python-format
msgid "The following package will be reinstalled (%(count)s):"
msgid_plural "The following packages will be reinstalled (%(count)s):"
msgstr[0] "以下のパッケージを再インストールします (%(count)s):"

#: ../aptdaemon/console.py:499
#, python-format
msgid "The following package has been kept back (%(count)s):"
msgid_plural "The following packages have been kept back (%(count)s):"
msgstr[0] "以下のパッケージはそのままです (%(count)s):"

#: ../aptdaemon/console.py:507
#, python-format
msgid "Need to get %sB of archives."
msgstr "%sB のアーカイブを取得する必要があります。"

#: ../aptdaemon/console.py:510
#, python-format
msgid "After this operation, %sB of additional disk space will be used."
msgstr "この操作を行うと、%sB の追加ディスク領域を使用します。"

#: ../aptdaemon/console.py:514
#, python-format
msgid "After this operation, %sB of additional disk space will be freed."
msgstr "この操作を行うと、%sB の追加ディスク領域が開放されます。"

#: ../aptdaemon/console.py:522 ../aptdaemon/console.py:524
msgid "Do you want to continue [Y/n]?"
msgstr "続けますか? [Y/n]"

#: ../aptdaemon/console.py:545
msgid ""
"To operate on more than one package put the package names in quotation "
"marks:\n"
"aptdcon --install \"foo bar\""
msgstr ""
"2 個以上のパッケージを操作するにはクォーテーションマークの間にパッケージ名を"
"入れてください:\n"
"aptdcon --install \"foo bar\""

#: ../aptdaemon/console.py:551
msgid "Refresh the cache"
msgstr "キャッシュを更新"

#: ../aptdaemon/console.py:554
msgid ""
"Try to resolve broken dependencies. Potentially dangerous operation since it "
"could try to remove many packages."
msgstr ""
"壊れた依存関係を修復しようとしています。この操作は多くのパッケージを削除する"
"可能性がある、危険な作業です。"

#: ../aptdaemon/console.py:559
msgid "Try to finish a previous incompleted installation"
msgstr "以前の不完全なインストール状態を終了させようとしています"

#: ../aptdaemon/console.py:563 ../aptdaemon/console.py:576
msgid "Install the given packages"
msgstr "指定されたパッケージをインストール"

#: ../aptdaemon/console.py:566
msgid "Reinstall the given packages"
msgstr "指定されたパッケージを再インストール"

#: ../aptdaemon/console.py:569
msgid "Remove the given packages"
msgstr "指定されたパッケージを削除"

#: ../aptdaemon/console.py:572
msgid "Remove the given packages including configuration files"
msgstr "設定ファイルを含めて指定されたパッケージを削除"

#: ../aptdaemon/console.py:579
msgid "Downgrade the given packages"
msgstr "指定されたパッケージでダウングレード"

#: ../aptdaemon/console.py:582
msgid "Deprecated: Please use --safe-upgrade"
msgstr "非推奨: --safe-upgrade を使用してください"

#: ../aptdaemon/console.py:586
msgid "Upgrade the system in a safe way"
msgstr "安全な方法でシステムをアップグレード"

#: ../aptdaemon/console.py:589
msgid "Upgrade the system, possibly installing and removing packages"
msgstr ""
"システムをアップグレードします。パッケージのインストールや削除が行われるかも"
"しれません。"

#: ../aptdaemon/console.py:593
msgid "Add the vendor to the trusted ones"
msgstr "信頼できるベンダーに追加する"

#: ../aptdaemon/console.py:596
msgid "Add the vendor keyid (also needs --keyserver)"
msgstr "ベンダーの鍵 ID を追加 (--keyserver も必要)"

#: ../aptdaemon/console.py:600
msgid "Use the given keyserver for looking up keys"
msgstr "鍵の検索に、指定された鍵サーバーを利用する"

#: ../aptdaemon/console.py:604
msgid "Add new repository from the given deb-line"
msgstr "指定された deb-line から新しいリポジトリを追加"

#: ../aptdaemon/console.py:608
msgid ""
"Specify an alternative sources.list.d file to which repositories should be "
"added."
msgstr ""
"どのリポジトリを追加するかは、他の sources.list.d ファイルを指定してくださ"
"い。"

#: ../aptdaemon/console.py:612
msgid "List trusted vendor keys"
msgstr "信頼されたベンダー鍵の一覧"

#: ../aptdaemon/console.py:615
msgid "Remove the trusted key of the given fingerprint"
msgstr "指定のフィンガープリントをもつ信頼済の鍵を削除"

#: ../aptdaemon/console.py:622
msgid ""
"Reconfigure installed packages. Optionally the minimum priority of questions "
"can be specified"
msgstr ""
"インストール済みのパッケージを再設定します。オプションで質問の優先度を最小に"
"するよう指定できます。"

#: ../aptdaemon/console.py:627
msgid "The minimum debconf priority of question to be displayed"
msgstr "質問の優先度が最小のdebconfのみ表示されます"

#: ../aptdaemon/console.py:631
msgid "Do not attach to the apt terminal"
msgstr "apt terminalをアタッチしないでください"

#: ../aptdaemon/console.py:635
msgid "Allow packages from unauthenticated sources"
msgstr "認証されていないソースからのパッケージ導入を許可する"

#: ../aptdaemon/console.py:639
msgid ""
"Show additional information about the packages. Currently only the version "
"number"
msgstr "パッケージの追加情報を表示します。現在はバージョン番号のみです。"

#: ../aptdaemon/console.py:647 ../aptdaemon/enums.py:532
msgid "Waiting for authentication"
msgstr "認証を待っています"

#: ../aptdaemon/core.py:2135
msgid "Do not shutdown the daemon because of inactivity"
msgstr "Do not shutdown the daemon because of inactivity"

#: ../aptdaemon/core.py:2140
msgid "Do not load any plugins"
msgstr "どのプラグインもロードしない"

#: ../aptdaemon/core.py:2144
msgid "Show internal processing information"
msgstr "Show internal processing information"

#: ../aptdaemon/core.py:2149
msgid "Quit and replace an already running daemon"
msgstr "Quit and replace an already running daemon"

#: ../aptdaemon/core.py:2154
msgid "Listen on the DBus session bus (Only required for testing"
msgstr "DBusセッションバスの接続を待ちます（テスト時のみ必要です"

#: ../aptdaemon/core.py:2158
msgid "Perform operations in the given chroot"
msgstr "指定されたchroot環境で操作を実行します"

#: ../aptdaemon/core.py:2163
msgid "Store profile stats in the specified file"
msgstr "Store profile stats in the specified file"

#: ../aptdaemon/core.py:2168
msgid "Do not make any changes to the system (Only of use to developers)"
msgstr "Do not make any changes to the system (Only of use to developers)"

#: ../aptdaemon/enums.py:337
msgid "Installed file"
msgstr "インストール済のファイル"

#: ../aptdaemon/enums.py:338
msgid "Installed packages"
msgstr "インストール済のパッケージ"

#: ../aptdaemon/enums.py:339
msgid "Added key from file"
msgstr "ファイルから鍵を追加しました"

#: ../aptdaemon/enums.py:340
msgid "Updated cache"
msgstr "キャッシュを更新しました"

#: ../aptdaemon/enums.py:341
msgid "Search done"
msgstr "検索が完了しました"

#: ../aptdaemon/enums.py:342
msgid "Removed trusted key"
msgstr "信頼された鍵を削除しました"

#: ../aptdaemon/enums.py:343
msgid "Removed packages"
msgstr "パッケージを削除しました"

#: ../aptdaemon/enums.py:344
msgid "Updated packages"
msgstr "パッケージを更新しました"

#: ../aptdaemon/enums.py:345
msgid "Upgraded system"
msgstr "システムをアップグレードしました"

#: ../aptdaemon/enums.py:346
msgid "Applied changes"
msgstr "変更を適用しました"

#: ../aptdaemon/enums.py:347
msgid "Repaired incomplete installation"
msgstr "不完全なインストール状態を修復しました"

#: ../aptdaemon/enums.py:348
msgid "Repaired broken dependencies"
msgstr "壊れている依存関係を修復しました"

#: ../aptdaemon/enums.py:349
msgid "Added software source"
msgstr "追加されたソフトウェアソース"

#: ../aptdaemon/enums.py:350
msgid "Enabled component of the distribution"
msgstr "ディストリビューションの指定されたコンポーネントを利用可能にしました"

#: ../aptdaemon/enums.py:351
msgid "Removed downloaded package files"
msgstr "ダウンロードしたパッケージファイルの削除"

#: ../aptdaemon/enums.py:352
msgid "Reconfigured installed packages"
msgstr "インストールしたパッケージの再設定"

#: ../aptdaemon/enums.py:356
msgid "Successful"
msgstr "成功しました"

#: ../aptdaemon/enums.py:357
msgid "Canceled"
msgstr "キャンセルされました"

#: ../aptdaemon/enums.py:358 ../aptdaemon/enums.py:569
msgid "Failed"
msgstr "失敗しました"

#: ../aptdaemon/enums.py:361
msgid "Installing file"
msgstr "ファイルをインストールしています"

#: ../aptdaemon/enums.py:362
msgid "Installing packages"
msgstr "パッケージをインストールしています"

#: ../aptdaemon/enums.py:363
msgid "Adding key from file"
msgstr "ファイルから鍵を追加しています"

#: ../aptdaemon/enums.py:364
msgid "Updating cache"
msgstr "キャッシュを更新しています"

#: ../aptdaemon/enums.py:365
msgid "Removing trusted key"
msgstr "信頼された鍵を削除しています"

#: ../aptdaemon/enums.py:366
msgid "Removing packages"
msgstr "パッケージを削除しています"

#: ../aptdaemon/enums.py:367
msgid "Updating packages"
msgstr "パッケージを更新しています"

#: ../aptdaemon/enums.py:368
msgid "Upgrading system"
msgstr "システムをアップグレードしています"

#: ../aptdaemon/enums.py:369 ../aptdaemon/enums.py:528
msgid "Applying changes"
msgstr "変更を適用しています"

#: ../aptdaemon/enums.py:370
msgid "Repairing incomplete installation"
msgstr "不完全なインストール状態を修復しています"

#: ../aptdaemon/enums.py:371
msgid "Repairing installed software"
msgstr "インストール済みのソフトウェアを修復しています"

#: ../aptdaemon/enums.py:372
msgid "Adding software source"
msgstr "ソフトウェアソースの追加"

#: ../aptdaemon/enums.py:373
msgid "Enabling component of the distribution"
msgstr "ディストリビューションの指定されたコンポーネントを利用可能にしています"

#: ../aptdaemon/enums.py:374
msgid "Removing downloaded package files"
msgstr "ダウンロードしたパッケージファイルの削除中"

#: ../aptdaemon/enums.py:375
msgid "Reconfiguring installed packages"
msgstr "インストールしたパッケージの再設定中"

#: ../aptdaemon/enums.py:376 ../aptdaemon/enums.py:517
msgid "Searching"
msgstr "検索"

#: ../aptdaemon/enums.py:380
msgid "Installation of the package file failed"
msgstr "パッケージのインストールに失敗しました"

#: ../aptdaemon/enums.py:381
msgid "Installation of software failed"
msgstr "ソフトウェアのインストールに失敗しました"

#: ../aptdaemon/enums.py:382
msgid "Adding the key to the list of trusted software vendors failed"
msgstr ""

#: ../aptdaemon/enums.py:384
msgid "Refreshing the software list failed"
msgstr "ソフトウェアリストの更新に失敗しました"

#: ../aptdaemon/enums.py:385
msgid "Removing the vendor from the list of trusted ones failed"
msgstr "信頼済みリストからのベンダーの削除に失敗しました"

#: ../aptdaemon/enums.py:387
msgid "Removing software failed"
msgstr "ソフトウェアの削除に失敗しました"

#: ../aptdaemon/enums.py:388
msgid "Updating software failed"
msgstr "ソフトウェアの更新に失敗しました"

#: ../aptdaemon/enums.py:389
msgid "Upgrading the system failed"
msgstr "システムのアップグレードに失敗しました"

#: ../aptdaemon/enums.py:390
msgid "Applying software changes failed"
msgstr "ソフトウェアの変更の適用に失敗しました"

#: ../aptdaemon/enums.py:391
msgid "Repairing incomplete installation failed"
msgstr "不完全なインストール状態の修復に失敗しました"

#: ../aptdaemon/enums.py:393
msgid "Repairing broken dependencies failed"
msgstr "壊れている依存関係の修復に失敗しました"

#: ../aptdaemon/enums.py:394
msgid "Adding software source failed"
msgstr "ソフトウェアソースの追加に失敗しました"

#: ../aptdaemon/enums.py:395
msgid "Enabling component of the distribution failed"
msgstr ""
"ディストリビューションの指定されたコンポーネントを利用可能にできませんでした"

#: ../aptdaemon/enums.py:397 ../aptdaemon/enums.py:398
msgid "Removing downloaded package files failed"
msgstr "ダウンロードしたパッケージファイルの削除に失敗しました"

#: ../aptdaemon/enums.py:399
msgid "Search failed"
msgstr "検索に失敗しました"

#: ../aptdaemon/enums.py:400
msgid "Adding license key"
msgstr "ライセンスキーの追加"

#: ../aptdaemon/enums.py:404 ../aptdaemon/enums.py:405
msgid "Check your Internet connection."
msgstr "インターネット接続を確認してください。"

#: ../aptdaemon/enums.py:406
msgid ""
"Check if you are using third party repositories. If so disable them, since "
"they are a common source of problems.\n"
"Furthermore run the following command in a Terminal: apt-get install -f"
msgstr ""
"サードパーティのリポジトリを使用しているかどうかを確認してください。利用して"
"いる場合、トラブルの原因になる場合があるので無効にしてください。\n"
"そのうえで端末から次のコマンドを実行してください: apt-get install -f"

#: ../aptdaemon/enums.py:411
msgid "The selected file may not be a GPG key file or it might be corrupt."
msgstr ""
"選択したファイルはGPG鍵ファイルではないか、壊れている可能性があります。"

#: ../aptdaemon/enums.py:413
msgid ""
"The selected key couldn't be removed. Check that you provided a valid "
"fingerprint."
msgstr ""
"選択された鍵は削除できません。有効なフィンガープリントを入力したか確認してく"
"ださい"

#: ../aptdaemon/enums.py:415
msgid ""
"Check if you are currently running another software management tool, e.g. "
"Synaptic or aptitude. Only one tool is allowed to make changes at a time."
msgstr ""
"他のソフトウェア管理ツールを現在実行していないかどうか確認してください。例: "
"Synaptic または aptitude。同時にソフトウェアの変更を行えるのは 1 つのツールの"
"みです。"

#: ../aptdaemon/enums.py:418
msgid ""
"This is a serious problem. Try again later. If this problem appears again, "
"please report an error to the developers."
msgstr ""
"重大な問題が発生しました。もう一度行い、再度問題が生じた場合には開発チームに"
"エラー報告をお願いします。"

#: ../aptdaemon/enums.py:421
msgid ""
"Check the spelling of the package name, and that the appropriate repository "
"is enabled."
msgstr ""
"パッケージ名のスペルや、パッケージに合ったリポジトリが有効になっているか確認"
"してください。"

#: ../aptdaemon/enums.py:423
msgid "There isn't any need for an update."
msgstr "アップデートを必要とするものはありません。"

#: ../aptdaemon/enums.py:424
msgid "There isn't any need for an installation"
msgstr "インストールを必要とするものはありません。"

#: ../aptdaemon/enums.py:426
msgid "There isn't any need for a removal."
msgstr "削除を必要とするものはありません。"

#: ../aptdaemon/enums.py:427
msgid ""
"You requested to remove a package which is an essential part of your system."
msgstr "削除を要求したパッケージはシステムの重要な部分に関わるものです。"

#: ../aptdaemon/enums.py:430
msgid ""
"The connection to the daemon was lost. Most likely the background daemon "
"crashed."
msgstr ""
"デーモンとの接続が切断されました。バックグラウンドデーモンがクラッシュした可"
"能性が極めて高いです。"

#: ../aptdaemon/enums.py:432
msgid "The installation or removal of a software package failed."
msgstr "ソフトウェアのインストールまたは削除が失敗しました。"

#: ../aptdaemon/enums.py:434
msgid "The requested feature is not supported."
msgstr "要求された機能はサポートされていません。"

#: ../aptdaemon/enums.py:435
msgid ""
"There seems to be a programming error in aptdaemon, the software that allows "
"you to install/remove software and to perform other package management "
"related tasks."
msgstr ""
"ソフトウェアをインストール/削除したり、他のパッケージ管理に関連したタスクを行"
"うソフトウェアである、aptdaemonのプログラミングエラーのようです。"

#: ../aptdaemon/enums.py:439
msgid ""
"This error could be caused by required additional software packages which "
"are missing or not installable. Furthermore there could be a conflict "
"between software packages which are not allowed to be installed at the same "
"time."
msgstr ""
"このエラーは必要な追加ソフトウェアパッケージが見つからないかインストールされ"
"ていないため発生したものです。そのうえ、同時にインストールできないソフトウェ"
"アパッケージの間で衝突が発生している可能性があります。"

#: ../aptdaemon/enums.py:445
msgid "This requires installing packages from unauthenticated sources."
msgstr ""
"この操作には認証されていないソースからのパッケージをインストールする必要があ"
"ります。"

#: ../aptdaemon/enums.py:447
msgid ""
"The installation could have failed because of an error in the corresponding "
"software package or it was cancelled in an unfriendly way. You have to "
"repair this before you can install or remove any further software."
msgstr ""
"関係のあるソフトウェアパッケージでエラーが発生したか、通常ではない方法で中断"
"されたためインストールに失敗した可能性があります。ソフトウェアをインストール"
"または削除する前に、この問題を修正する必要があります。"

#: ../aptdaemon/enums.py:453
msgid ""
"Please copy the file to your local computer and check the file permissions."
msgstr ""
"ファイルをローカルのコンピュータにコピーして、ファイルの権限をチェックしてく"
"ださい。"

#: ../aptdaemon/enums.py:456
msgid ""
"The installation of a package which violates the quality standards isn't "
"allowed. This could cause serious problems on your computer. Please contact "
"the person or organisation who provided this package file and include the "
"details beneath."
msgstr ""
"品質を満たしていない壊れたパッケージのインストールは許可されていません。コン"
"ピュータに深刻な問題を発生させる可能性があるからです。詳細については、この"
"パッケージを作成した人物か組織に連絡してください。"

#: ../aptdaemon/enums.py:463
msgid ""
"The downloaded license key which is required to run this piece of software "
"is not valid or could not be installed correctly.\n"
"See the details for more information."
msgstr ""
"このソフトウェアを実行するのに必要なダウンロード済みのライセンスキーが有効で"
"ないか、または正常にインストールされていません。\n"
"詳しい情報は詳細を確認してください。"

#: ../aptdaemon/enums.py:469
msgid "All available upgrades have already been installed."
msgstr "すべての利用可能なアップグレードはすでにインストールされています。"

#: ../aptdaemon/enums.py:471
msgid ""
"The license key which allows you to use this piece of software could not be "
"downloaded. Please check your network connection."
msgstr ""
"このソフトウェアの使用を許可するライセンスキーがダウンロードできませんでし"
"た。ネットワーク接続を確認してください。"

#: ../aptdaemon/enums.py:475
#, fuzzy
msgid "You don't have the required privileges to perform this action."
msgstr "このアクションを行う権限がありません。"

#: ../aptdaemon/enums.py:477
msgid ""
"You either provided a wrong password or cancelled the authorization.\n"
"Furthermore there could also be a technical reason for this error if you "
"haven't seen a password dialog: your desktop environment doesn't provide a "
"PolicyKit session agent."
msgstr ""

#: ../aptdaemon/enums.py:485
msgid "Failed to download package files"
msgstr "パッケージファイルのダウンロードに失敗しました。"

#: ../aptdaemon/enums.py:486
msgid "Failed to download repository information"
msgstr "リポジトリ情報のダウンロードに失敗しました。"

#: ../aptdaemon/enums.py:488
msgid "Package dependencies cannot be resolved"
msgstr "パッケージの依存性を解決できません。"

#: ../aptdaemon/enums.py:489
msgid "The package system is broken"
msgstr "パッケージシステムが壊れています。"

#: ../aptdaemon/enums.py:490
msgid "Key was not installed"
msgstr "鍵はインストールされませんでした"

#: ../aptdaemon/enums.py:491
msgid "Key was not removed"
msgstr "鍵は削除されませんでした"

#: ../aptdaemon/enums.py:492
msgid "Failed to lock the package manager"
msgstr "パッケージマネージャーのロックに失敗しました"

#: ../aptdaemon/enums.py:493
msgid "Failed to load the package list"
msgstr "パッケージ一覧の読み込みに失敗しました"

#: ../aptdaemon/enums.py:494
msgid "Package does not exist"
msgstr "パッケージが存在しません"

#: ../aptdaemon/enums.py:495
msgid "Package is already up to date"
msgstr "パッケージはすでに最新です"

#: ../aptdaemon/enums.py:496
msgid "Package is already installed"
msgstr "パッケージはインストール済です"

#: ../aptdaemon/enums.py:497
msgid "Package isn't installed"
msgstr "パッケージはインストールされていません"

#: ../aptdaemon/enums.py:498
msgid "Failed to remove essential system package"
msgstr "重要なシステムパッケージの削除に失敗しました"

#: ../aptdaemon/enums.py:500
msgid "Task cannot be monitored or controlled"
msgstr "タスクを監視またはコントロールすることができません"

#: ../aptdaemon/enums.py:501
msgid "Package operation failed"
msgstr "パッケージの操作に失敗しました"

#: ../aptdaemon/enums.py:502
msgid "Requires installation of untrusted packages"
msgstr "信頼されていないパッケージのインストールが必要です"

#: ../aptdaemon/enums.py:504
msgid "Previous installation hasn't been completed"
msgstr "以前のインストールが完了していません"

#: ../aptdaemon/enums.py:505
msgid "The package is of bad quality"
msgstr "パッケージの品質が悪いです"

#: ../aptdaemon/enums.py:506
msgid "Package file could not be opened"
msgstr "パッケージファイルを開けませんでした"

#: ../aptdaemon/enums.py:507
msgid "Not supported feature"
msgstr "サポートされていない機能です"

#: ../aptdaemon/enums.py:508
msgid "Failed to download the license key"
msgstr "ライセンスキーのダウンロードに失敗しました"

#: ../aptdaemon/enums.py:509
msgid "Failed to install the license key"
msgstr "ライセンスキーのインストールに失敗しました"

#: ../aptdaemon/enums.py:510
msgid "The system is already up to date"
msgstr "システムはすでに最新です"

#: ../aptdaemon/enums.py:511
msgid "You could not be authorized"
msgstr ""

#: ../aptdaemon/enums.py:512
msgid "You are not allowed to perform this action"
msgstr "このアクションを実行する権限がありません"

#: ../aptdaemon/enums.py:513
msgid "An unhandlable error occured"
msgstr "ハンドルできないエラーが発生しました"

#: ../aptdaemon/enums.py:516
msgid "Waiting for service to start"
msgstr "処理の開始を待っています"

#: ../aptdaemon/enums.py:518
msgid "Waiting"
msgstr "待機中"

#: ../aptdaemon/enums.py:519
msgid "Waiting for required medium"
msgstr "要求されたメディアを待っています"

#: ../aptdaemon/enums.py:520
msgid "Waiting for other software managers to quit"
msgstr "他のソフトウェアマネージャーの終了を待っています"

#: ../aptdaemon/enums.py:521
msgid "Waiting for configuration file prompt"
msgstr "設定ファイルのプロンプトを待っています"

#: ../aptdaemon/enums.py:523
msgid "Running task"
msgstr "タスクを実行中です"

#: ../aptdaemon/enums.py:524
msgid "Downloading"
msgstr "ダウンロード中です"

#: ../aptdaemon/enums.py:525
msgid "Querying software sources"
msgstr "ソフトウェアソースに問い合わせています"

#: ../aptdaemon/enums.py:526
msgid "Cleaning up"
msgstr "クリーンアップ中です"

#: ../aptdaemon/enums.py:529
msgid "Finished"
msgstr "終了しました"

#: ../aptdaemon/enums.py:530
msgid "Cancelling"
msgstr "キャンセルします"

#: ../aptdaemon/enums.py:531
msgid "Loading software list"
msgstr "ソフトウェアの一覧を読み込んでいます"

#. TRANSLATORS: %s is the name of a package
#: ../aptdaemon/enums.py:536
#, python-format
msgid "Installing %s"
msgstr "%s をインストールしています"

#. TRANSLATORS: %s is the name of a package
#: ../aptdaemon/enums.py:538
#, python-format
msgid "Configuring %s"
msgstr "%s を設定しています"

#. TRANSLATORS: %s is the name of a package
#: ../aptdaemon/enums.py:540
#, python-format
msgid "Removing %s"
msgstr "%s を削除しています"

#. TRANSLATORS: %s is the name of a package
#: ../aptdaemon/enums.py:542
#, python-format
msgid "Completely removing %s"
msgstr "%s を完全に削除しています"

#. TRANSLATORS: %s is the name of a package
#: ../aptdaemon/enums.py:544
#, python-format
msgid "Noting disappearance of %s"
msgstr "%sの消失を記録しています"

#. TRANSLATORS: %s is the name of a package
#: ../aptdaemon/enums.py:546
#, python-format
msgid "Running post-installation trigger %s"
msgstr "インストール後トリガ %s を実行しています"

#. TRANSLATORS: %s is the name of a package
#: ../aptdaemon/enums.py:548
#, python-format
msgid "Upgrading %s"
msgstr "%s をアップグレードしています"

#. TRANSLATORS: %s is the name of a package
#: ../aptdaemon/enums.py:550
#, python-format
msgid "Unpacking %s"
msgstr "%s を展開しています"

#. TRANSLATORS: %s is the name of a package
#: ../aptdaemon/enums.py:552
#, python-format
msgid "Preparing installation of %s"
msgstr "%s をインストールする準備をしています"

#. TRANSLATORS: %s is the name of a package
#: ../aptdaemon/enums.py:554
#, python-format
msgid "Preparing configuration of %s"
msgstr "%s を設定する準備をしています"

#. TRANSLATORS: %s is the name of a package
#: ../aptdaemon/enums.py:556
#, python-format
msgid "Preparing removal of %s"
msgstr "%s を削除する準備をしています"

#. TRANSLATORS: %s is the name of a package
#: ../aptdaemon/enums.py:558
#, python-format
msgid "Preparing complete removal of %s"
msgstr "%s を完全に削除する準備をしています"

#. TRANSLATORS: %s is the name of a package
#: ../aptdaemon/enums.py:560
#, python-format
msgid "Installed %s"
msgstr "%s をインストールしました"

#. TRANSLATORS: %s is the name of a package
#: ../aptdaemon/enums.py:562
#, python-format
msgid "Completely removed %s"
msgstr "%s を完全に削除しました"

#. TRANSLATORS: %s is the name of a package
#: ../aptdaemon/enums.py:564
#, python-format
msgid "Removed %s"
msgstr "%s を削除しました"

#: ../aptdaemon/enums.py:567
msgid "Done"
msgstr "完了"

#: ../aptdaemon/enums.py:568
msgid "Authentication failed"
msgstr "認証に失敗しました"

#: ../aptdaemon/enums.py:570
msgid "Fetching"
msgstr "取得しています"

#: ../aptdaemon/enums.py:571
msgid "Idle"
msgstr "待機中"

#: ../aptdaemon/enums.py:572
msgid "Network isn't available"
msgstr "ネットワークが利用できません"

#: ../aptdaemon/enums.py:704
#, python-format
msgid "Processing %s"
msgstr "%s を処理中"

#: ../aptdaemon/gtk3widgets.py:306
#, python-format
msgid "Downloaded %sB of %sB at %sB/s"
msgstr "%sB / %sB をダウンロード済（%sB/s）"

#: ../aptdaemon/gtk3widgets.py:311 ../aptdaemon/gtk3widgets.py:510
#, python-format
msgid "Downloaded %sB of %sB"
msgstr "%sB / %sB をダウンロード済"

#: ../aptdaemon/gtk3widgets.py:323
msgid "Details"
msgstr "詳細情報"

#: ../aptdaemon/gtk3widgets.py:474
msgid "File"
msgstr "ファイル"

#. TRANSLATORS: header of the progress download column
#: ../aptdaemon/gtk3widgets.py:479
msgid "%"
msgstr "%"

#: ../aptdaemon/gtk3widgets.py:515
#, python-format
msgid "Downloaded %sB"
msgstr "ダウンロード済み %sB"

#: ../aptdaemon/gtk3widgets.py:518
msgid "Downloaded"
msgstr "ダウンロード済"

#. TRANSLATORS: %s represents the name of a CD or DVD
#: ../aptdaemon/gtk3widgets.py:853
#, python-format
msgid "CD/DVD '%s' is required"
msgstr "'%s' という名のCD/DVDが必要です"

#. TRANSLATORS: %s is the name of the CD/DVD drive
#: ../aptdaemon/gtk3widgets.py:855
#, python-format
msgid ""
"Please insert the above CD/DVD into the drive '%s' to install software "
"packages from it."
msgstr ""
"パッケージをインストールするため、CD/DVDをドライブ '%s' に入れてください。"

#: ../aptdaemon/gtk3widgets.py:859 ../aptdaemon/gtk3widgets.py:880
msgid "C_ontinue"
msgstr "続行(_O)"

#: ../aptdaemon/gtk3widgets.py:931
msgid "Install"
msgstr "インストール"

#: ../aptdaemon/gtk3widgets.py:932
msgid "Reinstall"
msgstr "再インストール"

#: ../aptdaemon/gtk3widgets.py:933
msgid "Remove"
msgstr "削除"

#: ../aptdaemon/gtk3widgets.py:934
msgid "Purge"
msgstr "完全に削除"

#: ../aptdaemon/gtk3widgets.py:935
msgid "Upgrade"
msgstr "アップグレード"

#: ../aptdaemon/gtk3widgets.py:936
msgid "Downgrade"
msgstr "ダウングレード"

#: ../aptdaemon/gtk3widgets.py:937
msgid "Skip upgrade"
msgstr "アップグレードをスキップ"

#. If there is only one type of changes (e.g. only installs) expand the
#. tree
#. FIXME: adapt the title and message accordingly
#. FIXME: Should we have different modes? Only show dependencies, only
#. initial packages or both?
#: ../aptdaemon/gtk3widgets.py:948
msgid "Please take a look at the list of changes below."
msgstr "以下の変更点のリストを確認してください。"

#: ../aptdaemon/gtk3widgets.py:956
msgid "Additional software has to be installed"
msgstr "追加ソフトウェアをインストールする必要があります"

#: ../aptdaemon/gtk3widgets.py:958
msgid "Additional software has to be re-installed"
msgstr "追加ソフトウェアを再インストールする必要があります"

#: ../aptdaemon/gtk3widgets.py:960
msgid "Additional software has to be removed"
msgstr "追加ソフトウェアを削除する必要があります"

#: ../aptdaemon/gtk3widgets.py:962
msgid "Additional software has to be purged"
msgstr "完全に削除されようとしている追加のソフトウエア"

#: ../aptdaemon/gtk3widgets.py:964
msgid "Additional software has to be upgraded"
msgstr "追加ソフトウェアをアップグレードする必要があります"

#: ../aptdaemon/gtk3widgets.py:966
msgid "Additional software has to be downgraded"
msgstr "追加ソフトウェアをダウングレードする必要があります"

#: ../aptdaemon/gtk3widgets.py:968
msgid "Updates will be skipped"
msgstr "アップグレードはスキップされます"

#: ../aptdaemon/gtk3widgets.py:976
msgid "Additional changes are required"
msgstr "追加の変更が必要です"

#: ../aptdaemon/gtk3widgets.py:981
#, python-format
msgid "%sB will be downloaded in total."
msgstr "全部で %sB がダウンロードされます。"

#: ../aptdaemon/gtk3widgets.py:985
#, python-format
msgid "%sB of disk space will be freed."
msgstr "%sB のディスクスペースが開放されます。"

#: ../aptdaemon/gtk3widgets.py:989
#, python-format
msgid "%sB more disk space will be used."
msgstr "少なくとも %sB のディスクスペースが使用されます。"

#. TRANSLATORS: %s is a file path
#: ../aptdaemon/gtk3widgets.py:1061
#, python-format
msgid ""
"Replace your changes in '%s' with a later version of the configuration file?"
msgstr "変更されている '%s' を最新バージョンの設定ファイルで置き換えますか？"

#: ../aptdaemon/gtk3widgets.py:1063
msgid ""
"If you don't know why the file is there already, it is usually safe to "
"replace it."
msgstr ""
"そのファイルが存在している理由が分からない場合は、通常置き換えたほうが安全で"
"す。"

#: ../aptdaemon/gtk3widgets.py:1072
msgid "_Changes"
msgstr "変更(_C)"

#: ../aptdaemon/gtk3widgets.py:1075
msgid "_Keep"
msgstr "そのまま(_K)"

#: ../aptdaemon/gtk3widgets.py:1076
msgid "_Replace"
msgstr "置き換える(_R)"

#: ../aptdaemon/gtk3widgets.py:1179
msgid "_Details"
msgstr "詳細(_D)"

#. TRANSLATORS: %s is the name of a package manager
#: ../aptdaemon/lock.py:182
#, python-format
msgid "Waiting for %s to exit"
msgstr "%s の終了を待っています"

#. TRANSLATORS: %s is a list of package names
#: ../aptdaemon/progress.py:169
#, python-format
msgid "Downloading %(files)s"
msgid_plural "Downloading %(files)s"
msgstr[0] "ダウンロード中 %(files)s"

#. TRANSLATORS: the string is used as a fallback if we cannot
#. get the URI of a local repository
#: ../aptdaemon/progress.py:281 ../aptdaemon/progress.py:320
msgid "local repository"
msgstr "ローカルリポジトリ"

#. TRANSLATORS: %s is a list of repository names
#: ../aptdaemon/progress.py:284
#, python-format
msgid "Downloading from %s"
msgid_plural "Downloading from %s"
msgstr[0] "%s からダウンロードしています"

#. TRANSLATORS: repo is the name of a repository
#: ../aptdaemon/progress.py:324
#, python-format
msgid "Structure of %s"
msgstr "%s の構成"

#. TRANSLATORS: repo is the name of a repository
#: ../aptdaemon/progress.py:327
#, python-format
msgid "Description of %s"
msgstr "%s の詳細"

#. TRANSLATORS: repo is the name of a repository
#: ../aptdaemon/progress.py:330
#, python-format
msgid "Description signature of %s"
msgstr "%sの署名済み詳細ファイル"

#: ../aptdaemon/progress.py:335
#, python-format
msgid "Available packages from %s"
msgstr "%s で利用可能なパッケージ"

#: ../aptdaemon/progress.py:339
#, python-format
msgid "Available sources from %s"
msgstr "%s で利用可能なソース"

#. TRANSLATORS: repo is the name of a repository
#: ../aptdaemon/progress.py:342
#, python-format
msgid "Available translations from %s"
msgstr "%s で利用可能な翻訳"

#: ../aptdaemon/progress.py:359
#, python-format
msgid "Translations for %s (%s) from %s"
msgstr "%s（%s）用の%sの翻訳データ"

#. TRANSLATORS: %s is the name of a language. The second one is
#. the name of the repository
#: ../aptdaemon/progress.py:363
#, python-format
msgid "Translations for %s from %s"
msgstr "%s用の%sの翻訳データ"

#. TRANSLATORS: %s is the code of a language, e.g. ru_RU.
#. The second one is the name of the repository
#: ../aptdaemon/progress.py:368
#, python-format
msgid "Translations (%s) from %s"
msgstr "(%s)用の%sの翻訳データ"

#: ../aptdaemon/worker/aptworker.py:374 ../aptdaemon/worker/aptworker.py:671
#: ../aptdaemon/worker/aptworker.py:748 ../aptdaemon/worker/aptworker.py:791
#, python-format
msgid "Package %s isn't available"
msgstr "パッケージ %s は利用できません"

#: ../aptdaemon/worker/aptworker.py:379 ../aptdaemon/worker/aptworker.py:675
#: ../aptdaemon/worker/aptworker.py:752 ../aptdaemon/worker/aptworker.py:795
#, python-format
msgid "Package %s isn't installed"
msgstr "パッケージ %s はインストールされません"

#: ../aptdaemon/worker/aptworker.py:383
#, python-format
msgid "The version %s of %s isn't installed"
msgstr "バージョン %s の %s はインストールされていません"

#: ../aptdaemon/worker/aptworker.py:398
#, python-format
msgid "Package %s is already installed"
msgstr "パッケージ %s はインストール済みです"

#: ../aptdaemon/worker/aptworker.py:407 ../aptdaemon/worker/aptworker.py:821
#, python-format
msgid "The version %s of %s isn't available."
msgstr "バージョン %s の %s は利用できません。"

#. TRANSLATORS: %s is the URL of GnuPG
#. keyserver
#: ../aptdaemon/worker/aptworker.py:565
#, python-format
msgid "The keyserver URL is invalid: %s"
msgstr "キーサーバーのURLが無効です: %s"

#. TRANSLATORS: %s is the URL of GnuPG
#. keyserver
#: ../aptdaemon/worker/aptworker.py:571
#, python-format
msgid "Invalid protocol of the server: %s"
msgstr "サーバーのプロトコルが無効です: %s"

#. TRANSLATORS: %s is the id of a GnuPG key
#. e.g. E08ADE95
#: ../aptdaemon/worker/aptworker.py:579 ../aptdaemon/worker/aptworker.py:623
#, python-format
msgid "Invalid key id: %s"
msgstr "キーIDが無効です: %s"

#: ../aptdaemon/worker/aptworker.py:587
#, python-format
msgid ""
"Failed to download and install the key %s from %s:\n"
"%s"
msgstr ""
"キー %s を %s からダウンロードしてインストールするのに失敗しました:\n"
"%s"

#: ../aptdaemon/worker/aptworker.py:604
#, python-format
msgid "Key file %s couldn't be installed: %s"
msgstr "キーファイル %s はインストールできませんでした: %s"

#: ../aptdaemon/worker/aptworker.py:628
#, python-format
msgid "Key with fingerprint %s couldn't be removed: %s"
msgstr "フィンガープリント %s のキーを削除できませんでした: %s"

#: ../aptdaemon/worker/aptworker.py:679
#, python-format
msgid "Package %s cannot be removed."
msgstr "パッケージ %s は削除できません"

#: ../aptdaemon/worker/aptworker.py:683
#, python-format
msgid "The version %s of %s is not installed"
msgstr "バージョン %s の %s はインストールされていません"

#: ../aptdaemon/worker/aptworker.py:763
#, python-format
msgid "The former version %s of %s is already installed"
msgstr "以前のバージョン %s の %s はインストール済みです"

#: ../aptdaemon/worker/aptworker.py:768 ../aptdaemon/worker/aptworker.py:814
#, python-format
msgid "The version %s of %s is already installed"
msgstr "バージョン %s の %s はインストール済みです"

#: ../aptdaemon/worker/aptworker.py:775
#, python-format
msgid "The version %s of %s isn't available"
msgstr "バージョン %s の %s は利用できません"

#: ../aptdaemon/worker/aptworker.py:779
#, python-format
msgid "You need to specify a version to downgrade %s to"
msgstr "ダウングレードする %s のバージョンを指定してください"

#: ../aptdaemon/worker/aptworker.py:807
#, python-format
msgid "The later version %s of %s is already installed"
msgstr "最新バージョン %s の %s はインストール済みです"

#: ../aptdaemon/worker/aptworker.py:838
#, python-format
msgid "The package %s isn't available in the %s release."
msgstr "パッケージ %s は %s リリースでは利用できません。"

#: ../aptdaemon/worker/aptworker.py:1026
#, python-format
msgid "Package %s cannot be removed"
msgstr "パッケージ %s は削除できません"

#: ../aptdaemon/worker/aptworker.py:1123
msgid ""
"The package doesn't provide a valid Installed-Size control field. See Debian "
"Policy 5.6.20."
msgstr ""
"このパッケージは、正しいInstall-Sizeが記述されていません。Debian Policy "
"5.6.20を確認してください。"

#: ../aptdaemon/worker/aptworker.py:1265
msgid "The license key is empty"
msgstr "ライセンスキーが空です"

#: ../aptdaemon/worker/aptworker.py:1281
msgid "The license key is not allowed to contain executable code."
msgstr "ライセンスキーに実行コードを含めることはできません。"

#: ../aptdaemon/worker/aptworker.py:1290
#, python-format
msgid "The license key path %s is invalid"
msgstr "ライセンスキーのパス %s が無効です"

#: ../aptdaemon/worker/aptworker.py:1294
#, python-format
msgid "The license key already exists: %s"
msgstr "ライセンスキーはすでに存在しています： %s"

#: ../aptdaemon/worker/aptworker.py:1299
#, python-format
msgid ""
"The location of the license key is unsecure since it contains symbolic "
"links. The path %s maps to %s"
msgstr ""
"ライセンスキーの場所はシンボリックリンクを含んでいるため安全ではありません。"
"パス%sは%sにマップされています。"

#: ../aptdaemon/worker/aptworker.py:1307
#, python-format
msgid "The directory where to install the key to doesn't exist yet: %s"
msgstr "キーのインストール先のディレクトリは存在しません: %s"

#: ../aptdaemon/worker/aptworker.py:1318
#, python-format
msgid "Failed to write key file to: %s"
msgstr "キーの書き込みに失敗しました: %s"

#: ../aptdaemon/worker/aptworker.py:1353
msgid "The following packages have unmet dependencies:"
msgstr "以下のパッケージは依存関係を満たしていません:"

#: ../aptdaemon/worker/aptworker.py:1406
msgid "but it is a virtual package"
msgstr "しかし、仮想パッケージです"

#: ../aptdaemon/worker/aptworker.py:1409
msgid "but it is not installed"
msgstr "しかし、インストールされていません"

#: ../aptdaemon/worker/aptworker.py:1411
msgid "but it is not going to be installed"
msgstr "しかし、インストールされません"

#. TRANSLATORS: %s is a version number
#: ../aptdaemon/worker/aptworker.py:1415
#, python-format
msgid "but %s is installed"
msgstr "しかし、%s はインストール済みです"

#. TRANSLATORS: %s is a version number
#: ../aptdaemon/worker/aptworker.py:1419
#, python-format
msgid "but %s is to be installed"
msgstr "しかし、%s はインストールされます"

#~ msgid "Adding the key to the list of trused software vendors failed"
#~ msgstr "信頼済みソフトウェアベンダーリストへの鍵の追加に失敗しました"
